use_frameworks!

platform :ios, '9.0'

target 'ZLBridge_Example' do
  pod 'ZLBridge', :path => '../'

  target 'ZLBridge_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
#  pod trunk push ZLBridge.podspec --allow-warnings --verbose

end
